name: Build and deploy Python app to Azure Web App - nexusai

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies (for validation only)
        run: |
          pip install --upgrade pip
          pip install -r nexus-rag/requirements.txt

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_EA1A56C40C4B407A81FD7D42F6F47FD3 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_326C8123D3254BACBA214AD428137F10 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_852ED65476DC4ABDA2A79CAACA8F77FB }}

      - name: Deploy nexus-rag to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: nexusai
          slot-name: Production
          package: nexus-rag
